const quotes = [
  "Stay positive, vibes attract vibes ✨",
  "Keep shining, the world needs your light 🌞",
  "Chill and trust the process 🌱",
  "Good vibes only 🌈",
  "Dream it, do it 🚀",
  "You are the vibe 💫",
  "Happiness looks good on you 😎",
  "Collect memories, not things 📸",
  "Small steps every day 🌿",
  "Radiate love and light 💖",
  "Be the energy you want to attract 🌌",
  "Focus on the good 🌟",
  "Smile, it’s contagious 😊",
  "Create your own sunshine ☀️",
  "The best time for new beginnings is now 🌱",
  "Let your dreams be your wings 🕊️",
  "Do more of what makes you happy 🎶",
  "Be kind, it never goes out of style 💕",
  "Good energy is contagious 🔥",
  "Find joy in the little things 🌸",
  "You got this 💪",
  "Stay wild, moon child 🌙",
  "Shine bright like the stars ✨",
  "Peace begins with a smile 🌻",
  "Keep moving forward 🛤️",
  "Every day is a fresh start 🌅",
  "Do it with passion or not at all ❤️",
  "Choose joy 🌼",
  "Keep your head up 🌟",
  "Love yourself first 💎",
  "Progress, not perfection 📈",
  "Your vibe attracts your tribe 🤝",
  "Make today count ⏳",
  "Don’t quit, great things take time 🕰️",
  "Stay curious 🔍",
  "Life is better with laughter 😂",
  "Turn your dreams into plans ✍️",
  "Be fearless in pursuit of your goals 🏔️",
  "Gratitude changes everything 🙏",
  "Glow up, show up 🌺",
  "Positive mind, positive life 💭",
  "Inhale confidence, exhale doubt 🌬️",
  "Keep blooming 🌷",
  "Do it scared, but do it anyway 🦋",
  "You are enough 🌟",
  "Celebrate every little win 🎉",
  "Trust yourself 🧭",
  "Your future is created by today’s actions 🛠️",
  "Peace, love, and good vibes ✌️",
  "Let life surprise you 🎁",
  "Keep dancing, even when it rains 💃",
  "The best is yet to come 🌈",
  "Stay grounded, keep growing 🌳",
  "Follow the sunshine 🌞",
  "One step at a time 👣",
  "Keep your spirit light 🌬️",
  "Hustle and heart will set you apart ❤️‍🔥",
  "Your smile is your superpower 😁",
  "Stars can’t shine without darkness 🌌",
  "Never stop dreaming 🌠",
  "Choose peace over drama 🕊️",
  "You are stronger than you think 🐯",
  "Bloom where you are planted 🌻",
  "Shine today, glow tomorrow ✨",
  "Wake up and sparkle 💎",
  "Be the rainbow in someone’s cloud 🌈",
  "Keep hope alive 🔥",
  "Love more, worry less 💖",
  "Vibes speak louder than words 🎶",
  "Take it easy 🌊",
  "The sky is not the limit, your mind is 🚀",
  "Stay humble, stay kind 🌸",
  "Little things make big days 🌼",
  "Live simply, dream big 🏡",
  "Be unstoppable 🦾",
  "Joy is the best makeup 💄",
  "Think less, feel more 🌀",
  "Peaceful mind, grateful heart 🧘",
  "Keep glowing ✨",
  "Don’t just exist, live 🌍",
  "Turn your can’ts into cans 💪",
  "Shine even on your worst days 🌞",
  "Your energy introduces you before you speak 🔮",
  "Stay true to your vibe 🎧",
  "Celebrate life daily 🎊",
  "Be a voice, not an echo 🎤",
  "Magic happens outside your comfort zone ✨",
  "Smile at strangers, spread kindness 🌻",
  "Your journey is your strength 🛤️",
  "Keep faith, better days are coming 🌈",
  "Love yourself like you mean it 💕",
  "Be gentle with yourself 🦋",
  "Happiness is homemade 🍯",
  "Sunsets are proof that endings can be beautiful 🌅",
  "Don’t stress, do your best 🌿",
  "Live with intention 🎯",
  "Choose to shine 🌞",
  "Keep it simple, keep it real 🍃",
  "Where focus goes, energy flows 🎯"
];


function newQuote() {
    const randomIndex = Math.floor(Math.random() * quotes.length);
    document.getElementById("quote").innerText = quotes[randomIndex];
      
// Random background gradient
const colors = [
  "linear-gradient(135deg, #f093fb, #f5576c)",
  "linear-gradient(135deg, #5ee7df, #b490ca)",
  "linear-gradient(135deg, #ff9a9e, #fecfef)",
  "linear-gradient(135deg, #a1c4fd, #c2e9fb)",
  "linear-gradient(135deg, #d4fc79, #96e6a1)",
  "linear-gradient(135deg, #fbc2eb, #a6c1ee)",
  "linear-gradient(135deg, #fdfbfb, #ebedee)",
  "linear-gradient(135deg, #f6d365, #fda085)",
  "linear-gradient(135deg, #ffecd2, #fcb69f)",
  "linear-gradient(135deg, #a18cd1, #fbc2eb)",
  "linear-gradient(135deg, #fad0c4, #ffd1ff)",
  "linear-gradient(135deg, #ff9a9e, #fad0c4)",
  "linear-gradient(135deg, #ffdde1, #ee9ca7)",
  "linear-gradient(135deg, #89f7fe, #66a6ff)",
  "linear-gradient(135deg, #00c6ff, #0072ff)",
  "linear-gradient(135deg, #f7797d, #FBD786, #C6FFDD)",
  "linear-gradient(135deg, #12c2e9, #c471ed, #f64f59)",
  "linear-gradient(135deg, #ff6a00, #ee0979)",
  "linear-gradient(135deg, #43e97b, #38f9d7)",
  "linear-gradient(135deg, #fa709a, #fee140)",
  "linear-gradient(135deg, #f12711, #f5af19)",
  "linear-gradient(135deg, #b92b27, #1565C0)",
  "linear-gradient(135deg, #373B44, #4286f4)",
  "linear-gradient(135deg, #1f4037, #99f2c8)",
  "linear-gradient(135deg, #fc6076, #ff9a44, #ef9d43, #e75516)",
  "linear-gradient(135deg, #2980B9, #6DD5FA, #FFFFFF)",
  "linear-gradient(135deg, #e53935, #e35d5b)",
  "linear-gradient(135deg, #159957, #155799)",
  "linear-gradient(135deg, #2c3e50, #4ca1af)",
  "linear-gradient(135deg, #7F00FF, #E100FF)",
  "linear-gradient(135deg, #56CCF2, #2F80ED)",
  "linear-gradient(135deg, #ff7e5f, #feb47b)",
  "linear-gradient(135deg, #8E2DE2, #4A00E0)",
  "linear-gradient(135deg, #fc5c7d, #6a82fb)",
  "linear-gradient(135deg, #8360c3, #2ebf91)",
  "linear-gradient(135deg, #f953c6, #b91d73)",
  "linear-gradient(135deg, #009FFF, #ec2F4B)",
  "linear-gradient(135deg, #F7971E, #FFD200)",
  "linear-gradient(135deg, #8E2DE2, #FF416C)",
  "linear-gradient(135deg, #1D976C, #93F9B9)",
  "linear-gradient(135deg, #FF512F, #F09819)",
  "linear-gradient(135deg, #2c3e50, #bdc3c7)",
  "linear-gradient(135deg, #134E5E, #71B280)",
  "linear-gradient(135deg, #283c86, #45a247)",
  "linear-gradient(135deg, #000428, #004e92)"
];

document.body.style.background = colors[randomIndex];

    }
