const quotes = [
  "Stay positive, vibes attract vibes ✨",
  "Keep shining, the world needs your light 🌞",
  "Chill and trust the process 🌱",
  "Good vibes only 🌈",
  "Dream it, do it 🚀",
  "You are the vibe 💫",
  "Happiness looks good on you 😎",
  "Collect memories, not things 📸",
  "Small steps every day 🌿",
  "Radiate love and light 💖",
  "Be the energy you want to attract 🌌",
  "Focus on the good 🌟",
  "Smile, it’s contagious 😊",
  "Create your own sunshine ☀️",
  "The best time for new beginnings is now 🌱",
  "Let your dreams be your wings 🕊️",
  "Do more of what makes you happy 🎶",
  "Be kind, it never goes out of style 💕",
  "Good energy is contagious 🔥",
  "Find joy in the little things 🌸",
  "You got this 💪",
  "Stay wild, moon child 🌙",
  "Shine bright like the stars ✨",
  "Peace begins with a smile 🌻",
  "Keep moving forward 🛤️",
  "Every day is a fresh start 🌅",
  "Do it with passion or not at all ❤️",
  "Choose joy 🌼",
  "Keep your head up 🌟",
  "Love yourself first 💎",
  "Progress, not perfection 📈",
  "Your vibe attracts your tribe 🤝",
  "Make today count ⏳",
  "Don’t quit, great things take time 🕰️",
  "Stay curious 🔍",
  "Life is better with laughter 😂",
  "Turn your dreams into plans ✍️",
  "Be fearless in pursuit of your goals 🏔️",
  "Gratitude changes everything 🙏",
  "Glow up, show up 🌺",
  "Positive mind, positive life 💭",
  "Inhale confidence, exhale doubt 🌬️",
  "Keep blooming 🌷",
  "Do it scared, but do it anyway 🦋",
  "You are enough 🌟",
  "Celebrate every little win 🎉",
  "Trust yourself 🧭",
  "Your future is created by today’s actions 🛠️",
  "Peace, love, and good vibes ✌️",
  "Let life surprise you 🎁",
  "Keep dancing, even when it rains 💃",
  "The best is yet to come 🌈",
  "Stay grounded, keep growing 🌳",
  "Follow the sunshine 🌞",
  "One step at a time 👣",
  "Keep your spirit light 🌬️",
  "Hustle and heart will set you apart ❤️‍🔥",
  "Your smile is your superpower 😁",
  "Stars can’t shine without darkness 🌌",
  "Never stop dreaming 🌠",
  "Choose peace over drama 🕊️",
  "You are stronger than you think 🐯",
  "Bloom where you are planted 🌻",
  "Shine today, glow tomorrow ✨",
  "Wake up and sparkle 💎",
  "Be the rainbow in someone’s cloud 🌈",
  "Keep hope alive 🔥",
  "Love more, worry less 💖",
  "Vibes speak louder than words 🎶",
  "Take it easy 🌊",
  "The sky is not the limit, your mind is 🚀",
  "Stay humble, stay kind 🌸",
  "Little things make big days 🌼",
  "Live simply, dream big 🏡",
  "Be unstoppable 🦾",
  "Joy is the best makeup 💄",
  "Think less, feel more 🌀",
  "Peaceful mind, grateful heart 🧘",
  "Keep glowing ✨",
  "Don’t just exist, live 🌍",
  "Turn your can’ts into cans 💪",
  "Shine even on your worst days 🌞",
  "Your energy introduces you before you speak 🔮",
  "Stay true to your vibe 🎧",
  "Celebrate life daily 🎊",
  "Be a voice, not an echo 🎤",
  "Magic happens outside your comfort zone ✨",
  "Smile at strangers, spread kindness 🌻",
  "Your journey is your strength 🛤️",
  "Keep faith, better days are coming 🌈",
  "Love yourself like you mean it 💕",
  "Be gentle with yourself 🦋",
  "Happiness is homemade 🍯",
  "Sunsets are proof that endings can be beautiful 🌅",
  "Don’t stress, do your best 🌿",
  "Live with intention 🎯",
  "Choose to shine 🌞",
  "Keep it simple, keep it real 🍃",
  "Where focus goes, energy flows 🎯"
];


function newQuote() {
    const randomIndex = Math.floor(Math.random() * quotes.length);
    document.getElementById("quote").innerText = quotes[randomIndex];
      
// Random background gradient
const colors = [
    "linear-gradient(135deg, #f093fb, #f5576c)",
    "linear-gradient(135deg, #5ee7df, #b490ca)",
    "linear-gradient(135deg, #ff9a9e, #fecfef)",
    "linear-gradient(135deg, #a1c4fd, #c2e9fb)",
    "linear-gradient(135deg, #d4fc79, #96e6a1)"
    ];
document.body.style.background = colors[randomIndex];
    }